# Generated by Django 3.1.3 on 2021-11-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('app_name', models.CharField(max_length=1000)),
                ('app_id', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=1000)),
                ('version', models.CharField(default='1.0.0', max_length=6)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('rating_count', models.IntegerField()),
                ('free', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('size', models.CharField(max_length=5)),
                ('developer_id', models.CharField(max_length=500)),
                ('developer_website', models.URLField(default='')),
                ('developer_email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'apps',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=250)),
                ('emailid', models.EmailField(max_length=1000)),
                ('password', models.CharField(max_length=1000)),
                ('type', models.CharField(default='User', max_length=200)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('username', 'emailid'), name='unique_user'),
        ),
        migrations.AddConstraint(
            model_name='app',
            constraint=models.UniqueConstraint(fields=('app_name', 'app_id', 'version'), name='unique_app'),
        ),
    ]
