# Generated by Django 3.1.3 on 2021-11-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store_api', '0001_initial_manual'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='app',
            name='unique_app',
        ),
        migrations.AddConstraint(
            model_name='app',
            constraint=models.UniqueConstraint(fields=('app_name', 'app_id'), name='unique_app'),
        ),
    ]
